### ISSUE TITLE
Part of the code is missing

### ISSUE THREAD

**Issue by OneIsAll-w** [Meituan-AutoML/Twins#1]
Hello, I am very interested in your work, but I did not find the GSA part when reading the code. Is this part not open source yet?

**Comment by cxxgtxy** [comment]
I test the code and  it can work. 
Note that the naming of GSA is Attention (line 71 in gvt.py).  The naming of class doesn't follow the component naming in the paper because we want to use the pth.
Sorry for confusing and I will add more comments in next commit.

**Comment by OneIsAll-w** [comment]
The Attention class seems to be the SRA module of PVT, so the implementation of GSA is consistent with SRA?

**Comment by cxxgtxy** [comment]
GSA can be implemented by other functions such as AvgPooling, SepConv and several layers of Convolutions (ablation).
A single layer of convolution is used in our default implementation for simplicity.
GSA requires one key to summarize the information within a group, i.e., that key is firmly related to that group. 
SRA doesn't have the meaning of group.
The implementation is indeed the same when we use convolution within a group.

**Comment by OneIsAll-w** [comment]
I learned a lot, Thank you

**Comment by cxxgtxy** [comment]
Welcome. Thanks for your attention to our work.
Since the question is solved, I close the issue.
