### ISSUE TITLE
Runtime error for mmseg

### ISSUE THREAD

**Issue by lxtGH** [Meituan-AutoML/Twins#10]
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

Hi! Thanks for opensourcing code. 
When I use the Twins backbone in mmseg, I found this error. It seems that there are several parameters do not generate the loss.

**Comment by cxxgtxy** [comment]
The configure file 
https://github.com/Meituan-AutoML/Twins/blob/main/segmentation/configs/_base_/default_runtime.py
has set
find_unused_parameters = True.
If you include this file,  it acts like passing the keyword argument find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel.

**Comment by lxtGH** [comment]
Thanks for your reply. ~
