### ISSUE TITLE
flops calculation is not accurate.

### ISSUE THREAD

**Issue by tonysy** [Meituan-AutoML/Twins#11]
Hi, the get_flops.py doesn't consider the flops of self-attention, which is not accurate.
For Twins-PCPVT-S:
use get_flops.py given:
```
==============================
Input shape: (3, 512, 2048)
Flops: 162.66 GFLOPs
Params: 28.37 M
==============================
```

when use the fvcore.nn.flop_count(attention will be included), I get:

```
==============================
Input shape: (3, 512, 2048)
Flops: 225.98693683200003
Params: 28372862
==============================
```

**Comment by cxxgtxy** [comment]
We have noticed that difference.  And we will fix it in the next version.
Thanks!
