### ISSUE TITLE
mIoU eval method (got higher mIoU than provided)

### ISSUE THREAD

**Issue by zbwxp** [Meituan-AutoML/Twins#14]
For the 
ALTGVT-Large model on ADE20k dataset, the reported single scale mIoU in the page says 48.8
However, I used the mmsegmentation default evaluation code and got 49.07   **(higher??)**

(I am using default test_pipeline  img_scale= (2048, 512) , mode='whole')
I used a single GPU for single scale inference.

Could you please have a look at this?

Thank you

**Comment by cxxgtxy** [comment]
Can you report the version of mmsegmentation?

**Comment by zbwxp** [comment]
The most recent v0.14.0 released in 06/02/2021.

**Comment by cxxgtxy** [comment]
The released training log indicates the miOU of AlTGVT large is 48.8.
Have you tried other models using your environment?
