### ISSUE TITLE
how to install the module mc?

### ISSUE THREAD

**Issue by zhukuan96** [Meituan-AutoML/Twins#15]

**Comment by cxxgtxy** [comment]
You can proceed by following the README.md.
Omit mc.

**Comment by zhukuan96** [comment]
Sorry, but it is too slow if not using the memorycache.
I don't use mc because it's fast on my machine.

**Comment by zhukuan96** [comment]
It is better if you can provide the memory cached method, or I have to solve this with other repo

**Comment by cxxgtxy** [comment]
I don't use mc because it's  fast on my training servers without it.
I recommend you use pillow-simd to speed up the IO.
