### ISSUE TITLE
What is the difference between `GSA` in Twins and `SRA` in PVT?

### ISSUE THREAD

**Issue by pawopawo** [Meituan-AutoML/Twins#16]
What is the difference between `GSA` in Twins and `SRA` in PVT?

**Comment by cxxgtxy** [comment]
Please see https://github.com/Meituan-AutoML/Twins/issues/5

**Comment by pawopawo** [comment]
```
        if sr_ratio > 1:
            self.sr = nn.Conv2d(dim, dim, kernel_size=sr_ratio, stride=sr_ratio)
            self.norm = nn.LayerNorm(dim)
```

谢谢回复～但还是没有看出和SRA的区别啊，代码里GSA和SRA都是通过上面这样进行下采样

**Comment by cxxgtxy** [comment]
It's just an implementation. 
The role of GSA is exchanging information among different groups.  In fact, you can also use normal self attention without reduced keys. We use reduced key to summary information  within a group. And you can also use max or average operation.
