### ISSUE TITLE
Some confusion about warmup strategy

### ISSUE THREAD

**Issue by TingquanGao** [Meituan-AutoML/Twins#19]
In the log you provided, I find that the warmup epochs number is not 5 and linear warmup start at the second epoch. This is inconsistent with paper:
> We use a linear warm-up in the first five epochs ... 

https://github.com/Meituan-AutoML/Twins/blob/37f9dbf1aa2181062f1ce880b952af2875f1b79f/logs/svt_s.txt#L1-L7

Why? 
Thx.

**Comment by cxxgtxy** [comment]
We use the same setting as DeiT, whose lr schedule strategy is based on the timm lib.
from timm.scheduler import create_scheduler
Pay attention to the --warmup-lr and --min-lr args.

We suggest you read the code, especially the code of  create_scheduler.

Thanks.

**Comment by TingquanGao** [comment]
Thx for your reply.
