### ISSUE TITLE
The weight  'pcpvt_base.pth' which is trained on Ade20k dataset can't be download.

### ISSUE THREAD

**Issue by nizhenliang** [Meituan-AutoML/Twins#2]

**Comment by cxxgtxy** [comment]
Thanks!
The checkpoint is lost and we rerun the training. We will upload it ASAP.

**Comment by cxxgtxy** [comment]
We already update the checkpoint and log for pcpvt-base.
Please have a look.

**Comment by cxxgtxy** [comment]
Since the problem is solved, I close the issue.
