### ISSUE TITLE
学习率

### ISSUE THREAD

**Issue by pawopawo** [Meituan-AutoML/Twins#22]
https://github.com/Meituan-AutoML/Twins/blob/4700293a2d0a91826ab357fc5b9bc1468ae0e987/main.py#L263

在代码中，lr会跟随batch size线性调整。 但wramup-lr和min-lr为什么不用调整呢？

希望能够得到帮助，感谢～～～

**Comment by cxxgtxy** [comment]
wramup-lr和min-lr对batchsize不敏感
