### ISSUE TITLE
请教调用ALTGVT问题

### ISSUE THREAD

**Issue by wfs123456** [Meituan-AutoML/Twins#23]
您好，请教一下  调用分类任务中的ALTGVT时，提示 类GroupBlock重载父类TimmBlock时多写了一个参数，报错如下：
super(GroupBlock, self).__init__(dim, num_heads, mlp_ratio, qkv_bias, qk_scale, drop, attn_drop,
TypeError: __init__() takes from 3 to 10 positional arguments but 11 were given

查询TimmBlock后发现 其并没有qk_scale这个参数，请问这个bug如何解决呢

**Comment by cxxgtxy** [comment]
我猜是由于你安装的timm不是0.3.2

**Comment by wfs123456** [comment]
> 我猜是由于你安装的timm不是0.3.2

原来timm库不向下兼容，感谢美团大佬指导

**Comment by wfs123456** [comment]
> 我猜是由于你安装的timm不是0.3.2

原来timm库不向下兼容，感谢美团大佬指导

**Comment by cxxgtxy** [comment]
> > 我猜是由于你安装的timm不是0.3.2
> 
> 原来timm库不向下兼容，感谢美团大佬指导

问题解决后，可以close这个issue
