### ISSUE TITLE
Large模型，drop-path设置为0.5训练15个epoch后，出现其中一张GPU卡住利用率为0问题

### ISSUE THREAD

**Issue by liwei109** [Meituan-AutoML/Twins#25]
Large模型，drop-path设置为0.5训练15个epoch后，出现其中一张GPU卡住利用率为0问题，设置为0.3时则不存在该问题

**Comment by cxxgtxy** [comment]
这是常见的nan问题。
在训练vit large这个容量的模型时候，有时候（不一定发生）会因为fp16溢出发生这种现象。从个人经验看，经常出现在warmup后几个epoch，一般只会出现一次。
个人常用的有效方法包括：
1.在发生nan时候而卡住时候，采用fp32 resume训练完这个epoch，后面再切换成fp16.
2.grad norm设置小一点
3.降低dropath，但这个影响正则的强度，可能会稍微影响点精度
其中1基本都work，2很多时候有用，3不推荐用。

**Comment by liwei109** [comment]
但是代码中，分类任务的训练不涉及fp16噻，只有检测任务才涉及fp16还是32的问题。

**Comment by liwei109** [comment]
另外，关于您代码中所提到的main.py中line 333 提到的set_training_mode=args.finetune == ''  # keep in eval mode during finetuning这个备注，是在用224预训练模型finetune 384时用到的么，finetune的时候采用eval模式么？

**Comment by cxxgtxy** [comment]
> 但是代码中，分类任务的训练不涉及fp16噻，只有检测任务才涉及fp16还是32的问题。

不是啊。amp默认是打开的，分类也用的

**Comment by cxxgtxy** [comment]
> 另外，关于您代码中所提到的main.py中line 333 提到的set_training_mode=args.finetune == '' # keep in eval mode during finetuning这个备注，是在用224预训练模型finetune 384时用到的么，finetune的时候采用eval模式么？

eval没法finetune的。
