### ISSUE TITLE
A little confusion about GSA

### ISSUE THREAD

**Issue by TimHo0331** [Meituan-AutoML/Twins#4]
Hi, I am reading your concise but effective work. Since I am not in the field of computer vision, I have a narrow question about the GSA module:
After the global sub-sampled attention, the size of feature map is reduced to m*n, how do you resume it to the original size?

Another question is, have you tried the global max pooling as the sub-sample function?

Thank you!

**Comment by cxxgtxy** [comment]
1. The size of the generated feature map depends on the query. We don't reduce the number of queries therefore the size of the feature map doesn't change.
2. We don't try max pooling, but we test global average pooling (ablation study). It seems learnable sample function slightly outperforms global average pooling.
