### ISSUE TITLE
Run Train in Windows10，ERROR

### ISSUE THREAD

**Issue by KangolHsu** [Meituan-AutoML/Twins#6]
run train script in windows10，error ：

yapf.yapflib.verifier.InternalError: (unicode error) 'unicodeescape' codec can't decode bytes in position 9-10: truncated \uXXXX escape (<string>, line 1)

**Comment by cxxgtxy** [comment]
Hi. We suggest running our code on Linux environment.

**Comment by duduzai2019** [comment]
I have a same probelm, How can we handdle it in windows 10?
