### ISSUE TITLE
About the code stage

### ISSUE THREAD

**Issue by coocooon** [Meituan-AutoML/Twins#7]
![2021-05-19 15-45-33 的屏幕截图](https://user-images.githubusercontent.com/64255092/118776388-846b8980-b8ba-11eb-8136-a9cba036f536.png)
![2021-05-19 15-56-40 的屏幕截图](https://user-images.githubusercontent.com/64255092/118776926-18d5ec00-b8bb-11eb-99b4-cdf963fed631.png)

Dear author, I have seen that there are steps stage1,2,3 and 4 in your Twin paper. I want to output the results of these 4 stages respectively, but I can't find them in the code. I am looking forward to your reply.

**Comment by cxxgtxy** [comment]
Hi. You can see the gvt.py code (line 431) in the segmentation, where multi-stage information is used.
